package com.hamilton.bean;

import java.util.Objects;

public class Community{
    private int communityID; // maybe autogenerated by database??
    private String communityOwnerName;
    private int communityOwnerID;
    private String communityName;
    private String communityInfo;

    public Community(String ownerName, int ownerID, String communityName, String communityDescription) {
        this.communityOwnerName = ownerName;
        this.communityOwnerID = ownerID;
        this.communityName = communityName;
        this.communityInfo = communityDescription;
    }

    public Community(){ //default constructor

    }

    public String getCommunityInfo() {
        return communityInfo;
    }

    public void setCommunityInfo(String communityInfo) {
        this.communityInfo = communityInfo;
    }

    public int getCommunityID() {
        return communityID;
    }

    public void setCommunityID(int communityID) {
        this.communityID = communityID;
    }

    public String getCommunityOwnerName() {
        return communityOwnerName;
    }

    public void setCommunityOwnerName(String communityOwnerName) {
        this.communityOwnerName = communityOwnerName;
    }

    public int getCommunityOwnerID() {
        return communityOwnerID;
    }

    public void setCommunityOwnerID(int communityOwnerID) {
        this.communityOwnerID = communityOwnerID;
    }

    public String getCommunityName() {
        return communityName;
    }

    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Community community = (Community) o;
        return communityID == community.communityID && communityOwnerID == community.communityOwnerID && Objects.equals(communityOwnerName, community.communityOwnerName) && Objects.equals(communityName, community.communityName) && Objects.equals(communityInfo, community.communityInfo);
    }

}
