package com.hamilton.bean;

import java.sql.Date;
import java.util.Objects;

public class Doctor extends User{
    private int clinic_ID;
    private int doctor_ID; // auto generated by database
    private boolean isApproved;
    private int communityID;


    public Doctor(String name, String email, String password, Date birthdate,
                  String address, String socialSecurityNumber, int CommunityID, int clinic_ID, boolean isApproved) {
        super(name, email, password, birthdate, address, socialSecurityNumber);
        this.clinic_ID = clinic_ID;
        this.isApproved = isApproved;
        this.communityID = CommunityID;
    }

    public Doctor() {

    }

    public Doctor( User user, int CommunityID, int clinic_ID, boolean isApproved) {
        super(user.getName(), user.getEmail(), user.getPassword(), user.getBirthdate(), user.getAddress(), user.getSocialSecurityNumber());
        this.clinic_ID = clinic_ID;
        this.isApproved = isApproved;
        this.communityID = CommunityID;
    }

    public Doctor(int doctor_ID, String name, String email, String password, Date birthdate,
                  String address, String socialSecurityNumber, int CommunityID, int clinic_ID, boolean isApproved) {
        super(name, email, password, birthdate, address, socialSecurityNumber);
        this.doctor_ID = doctor_ID;
        this.clinic_ID = clinic_ID;
        this.isApproved = isApproved;
        this.communityID = CommunityID;
    }

    public boolean isApproved() {
        return isApproved;
    }

    public void setApproved(boolean approved) {
        isApproved = approved;
    }

    public int getDoctor_ID() {
        return doctor_ID;
    }

    public void setDoctor_ID(int doctor_ID) {
        this.doctor_ID = doctor_ID;
    }

    public int getClinic_ID() {
        return clinic_ID;
    }

    public void setClinic_ID(int clinic_ID) {
        this.clinic_ID = clinic_ID;
    }

    public int getCommunityID() {
        return communityID;
    }

    public void setCommunityID(int communityID) {
        this.communityID = communityID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Doctor doctor = (Doctor) o;
        return clinic_ID == doctor.clinic_ID && doctor_ID == doctor.doctor_ID && isApproved == doctor.isApproved && communityID == doctor.communityID;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clinic_ID, doctor_ID, isApproved, communityID);
    }
}
