package com.hamilton.bean;

import java.sql.Date;
import java.util.Objects;

public class Patient extends User{
    private int familyID;
    private int previousFamilyID;
    private int patientID; //auto generated by database
    private int communityID;
    private int clinicID;
    private boolean isApproved;

    public Patient( String name, String email, String password, Date birthdate, String address,
                    String socialSecurityNumber, int CommunityID, int familyID, int previousFamilyID, int clinicID) {
        super( name, email, password, birthdate, address, socialSecurityNumber);
        this.familyID = familyID;
        this.previousFamilyID = previousFamilyID;
        this.communityID = CommunityID;
        this.clinicID = clinicID;
    }

    public Patient(){//default Constructor

    }

    public Patient( User user, int CommunityID, int familyID, int previousFamilyID, int clinicID) {
        super(user.getName(), user.getEmail(), user.getPassword(), user.getBirthdate(), user.getAddress(), user.getSocialSecurityNumber());
        this.familyID = familyID;
        this.previousFamilyID = previousFamilyID;
        this.communityID = CommunityID;
        this.clinicID = clinicID;
    }


    public Patient( int patientID, String name, String email, String password, Date birthdate, String address,
                    String socialSecurityNumber, int CommunityID, int familyID, int previousFamilyID, boolean isApproved, int clinicID) {
        super( name, email, password, birthdate, address, socialSecurityNumber);
        this.familyID = familyID;
        this.previousFamilyID = previousFamilyID;
        this.communityID = CommunityID;
        this.isApproved = isApproved;
        this.patientID = patientID;
        this.clinicID = clinicID;
    }

    public int getClinicID() {
        return clinicID;
    }

    public void setClinicID(int clinicID) {
        this.clinicID = clinicID;
    }

    public int getPatientID() {
        return patientID;
    }

    public void setPatientID(int patientID) {
        this.patientID = patientID;
    }

    public int getFamilyID() {
        return familyID;
    }

    public void setFamilyID(int familyID) {
        this.familyID = familyID;
    }

    public int getPreviousFamilyID() {
        return previousFamilyID;
    }

    public void setPreviousFamilyID(int previousFamilyID) {
        this.previousFamilyID = previousFamilyID;
    }
    public int getCommunityID() {
        return communityID;
    }

    public void setCommunityID(int communityID) {
        this.communityID = communityID;
    }

    public boolean isApproved() {
        return isApproved;
    }

    public void setApproved(boolean approved) {
        isApproved = approved;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Patient patient = (Patient) o;
        return familyID == patient.familyID && previousFamilyID == patient.previousFamilyID && patientID == patient.patientID && communityID == patient.communityID && isApproved == patient.isApproved;
    }

    @Override
    public int hashCode() {
        return Objects.hash(familyID, previousFamilyID, patientID, communityID, isApproved);
    }
}
